import {
	Dashboard,
	Landing,
	Login,
	Almacenes,
	Articulos,
	Clientes,
	Empresas,
	Perfil,
	Proveedores,
	Usuarios,
	CrearArticulo,
	CrearAlmacen,
	CrearCliente,
	CrearEmpresa,
	CrearProveedor,
	CrearUsuario,
	Produccion,
	Inicio,
	Consulta,
	ProvArticulos,
} from "@/views"

import { IoPieChartSharp, IoMedical } from "react-icons/io5"
import { FaWarehouse, FaUsers, FaHome } from "react-icons/fa"
import { BsHospitalFill } from "react-icons/bs"
import { MdFactory, MdInventory } from "react-icons/md"
import { GiPelvisBone } from "react-icons/gi"
import { AiFillProduct } from "react-icons/ai"

export const completeRoutes = [
	{
		route: "/",
		title: "Landing",
		component: Landing,
		menu: false,
		icon: false,
		auth: "none",
		type: "none",
	},
	{
		route: "/login",
		title: "Login",
		component: Login,
		menu: false,
		icon: false,
		auth: "Not Authenticated",
		type: "none",
	},
	{
		route: "/main",
		title: "Inicio",
		component: Inicio,
		menu: true,
		icon: FaHome,
		auth: "Authenticated",
		type: "Productivo",
	},
	{
		route: "/dashboard",
		title: "Dashboard",
		component: Dashboard,
		menu: true,
		icon: IoPieChartSharp,
		auth: "Authenticated",
		type: "Productivo",
		grant: "dshb.viewWeb",
	},
	{
		route: "/consulta/reportes",
		title: "Consulta",
		component: Consulta,
		menu: true,
		icon: MdInventory,
		auth: "Authenticated",
		type: "Productivo",
	},
	{
		route: "/consulta/inventario",
		title: "Consulta Inventario",
		component: Consulta,
		menu: true,
		icon: MdInventory,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/consulta/movimientos",
		title: "Consulta Movimientos",
		component: Consulta,
		menu: true,
		icon: MdInventory,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/produccion/movimientos",
		title: "Producción",
		component: Produccion,
		menu: true,
		icon: AiFillProduct,
		auth: "Authenticated",
		type: "Productivo",
	},
	{
		route: "/produccion/captura-codigos-barra",
		title: "Producción Códigos de Barras",
		component: Produccion,
		menu: false,
		icon: IoMedical,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/produccion/captura-lotes",
		title: "Producción Lotes",
		component: Produccion,
		menu: false,
		icon: IoMedical,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/articulos",
		title: "Artículos",
		component: Articulos,
		menu: true,
		icon: IoMedical,
		auth: "Authenticated",
		type: "Catálogos",
		grant: "produc.viewWeb",
	},
	{
		route: "/articulos/crear-articulo",
		title: "Artículos",
		component: CrearArticulo,
		menu: false,
		icon: IoMedical,
		auth: "Authenticated",
		type: "none",
		grant: "produc.create",
	},
	{
		route: "/articulos/modificar-articulo/:id",
		title: "Artículos",
		component: CrearArticulo,
		menu: false,
		icon: IoMedical,
		auth: "Authenticated",
		type: "none",
		grant: "produc.modify",
	},
	{
		route: "/almacenes",
		title: "Almacenes",
		component: Almacenes,
		menu: true,
		icon: FaWarehouse,
		auth: "Authenticated",
		type: "Catálogos",
		grant: "alm.viewWeb",
	},
	{
		route: "/almacenes/crear-almacen",
		title: "Almacenes",
		component: CrearAlmacen,
		menu: true,
		icon: FaWarehouse,
		auth: "Authenticated",
		type: "none",
		grant: "alm.create",
	},
	{
		route: "/almacenes/modificar-almacen/:id",
		title: "Almacenes",
		component: CrearAlmacen,
		menu: true,
		icon: FaWarehouse,
		auth: "Authenticated",
		type: "none",
		grant: "alm.modify",
	},
	{
		route: "/proveedores",
		title: "Proveedores",
		component: Proveedores,
		menu: true,
		icon: GiPelvisBone,
		auth: "Authenticated",
		type: "Catálogos",
		grant: "provider.viewWeb",
	},
	{
		route: "/proveedores/crear-proveedor",
		title: "Proveedores",
		component: CrearProveedor,
		menu: true,
		icon: GiPelvisBone,
		auth: "Authenticated",
		type: "none",
		grant: "provider.create",
	},
	{
		route: "/proveedores/modificar-proveedor/:id",
		title: "Proveedores",
		component: CrearProveedor,
		menu: true,
		icon: GiPelvisBone,
		auth: "Authenticated",
		type: "none",
		grant: "provider.modify",
	},
	{
		route: "/proveedores/agrega-articulos-proveedor/:id",
		title: "Proveedores",
		component: ProvArticulos,
		menu: true,
		icon: GiPelvisBone,
		auth: "Authenticated",
		type: "none",
		grant: "provider.create",
	},
	{
		route: "/clientes",
		title: "Clientes",
		component: Clientes,
		menu: true,
		icon: BsHospitalFill,
		auth: "Authenticated",
		type: "Catálogos",
		grant: "client.viewWeb",
	},
	{
		route: "/clientes/crear-cliente",
		title: "Clientes",
		component: CrearCliente,
		menu: true,
		icon: BsHospitalFill,
		auth: "Authenticated",
		type: "none",
		grant: "client.create",
	},
	{
		route: "/clientes/modificar-cliente/:id",
		title: "Clientes",
		component: CrearCliente,
		menu: true,
		icon: BsHospitalFill,
		auth: "Authenticated",
		type: "none",
		grant: "client.modify",
	},
	{
		route: "/empresas",
		title: "Empresas",
		component: Empresas,
		menu: true,
		icon: MdFactory,
		auth: "Authenticated",
		type: "Catálogos",
		grant: "empr.viewMenu",
	},
	{
		route: "/empresas/crear-empresa",
		title: "Empresas",
		component: CrearEmpresa,
		menu: true,
		icon: MdFactory,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/empresas/modificar-empresa/:id",
		title: "Empresas",
		component: CrearEmpresa,
		menu: true,
		icon: MdFactory,
		auth: "Authenticated",
		type: "none",
	},

	{
		route: "/mi-perfil",
		title: "Perfil",
		component: Perfil,
		menu: false,
		icon: false,
		auth: "Authenticated",
		type: "none",
	},
	{
		route: "/usuarios",
		title: "Usuarios",
		component: Usuarios,
		menu: true,
		icon: FaUsers,
		auth: "Authenticated",
		type: "Administración",
		grant: "users.viewWeb",
	},
	{
		route: "/usuarios/crear-usuario",
		title: "Usuarios",
		component: CrearUsuario,
		menu: true,
		icon: FaUsers,
		auth: "Authenticated",
		type: "none",
		grant: "users.create",
	},
	{
		route: "/usuarios/modificar-usuario/:id",
		title: "Usuarios",
		component: CrearUsuario,
		menu: true,
		icon: FaUsers,
		auth: "Authenticated",
		type: "none",
	},
]
